controllers:
    resource: ../src/Controller/
    type: attribute

app_reset_password_request:
    path: /reset-password
    controller: SymfonyCasts\Bundle\ResetPassword\Controller\ResetPasswordController::request
